target "MHealth" do
use_frameworks!
pod 'Alamofire', '~> 3.1.4'
pod 'SwiftyJSON', '~> 2.3.2'
pod 'ObjectMapper', '~> 1.3'
pod 'SwiftSpinner', '~> 0.6'
platform :ios, '7.0'
pod 'SDWebImage', '~>3.8'
end